### ISSUE TITLE
Savon 2.10.1 updates automatically to 2.4.1, breaks everything

### ISSUE THREAD

**Issue by bobber205** [savonrb/httpi#148]
The latest minor release, 2.4.1 of httpi, I think removes the headers methods?
Because everytime I call call_service with `savon` I get the follow error

```
undefined method `headers' for #<HTTP::Client:0x000000111872f0>
```

Was this method really removed? I hadn't run `bundle update` since june 18th, so this was a too close for comfort production breaking change.

**Comment by rogerleite** [comment]
Hi Alex! This is weird, i don't remembet anything related to headers ...
Could you send the exception backtrace?

Sorry for the trouble.
Em 24/06/2015 18:39, "Alex Wait" <notifications@github.com> escreveu:

**Comment by rogerleite** [comment]
Hi @bobber205! You can change your httpi version to git master?

**Comment by bobber205** [comment]
Exactly, I can change it. But this minor release, which happens whenever someone run bundles update, breaks all of savon.

**Comment by bobber205** [comment]
I just reproduced the error but there is no visible backtrace. 
But it's happening from the call to a savon client instance's `call` method.

**Comment by rogerleite** [comment]
Could you please change httpi version on your Gemfile, something like:

```
gem 'httpi', git: 'git@github.com:savonrb/httpi.git'
```

I just want to be sure this issue is fixed by #149, before releasing new minor version.

Thanks Alex.

**Comment by bobber205** [comment]
Using `59eb83b7f02e58d9c4167eda81ada7a5072db68d` revision of httpi and still getting

```
 NoMethodError:
       undefined method `headers' for #<HTTP::Client:0x0000000f49c410>
     # ./vendor/cache/httpi-59eb83b7f02e/lib/httpi/adapter/http.rb:72:in `create_client'
     # ./vendor/cache/httpi-59eb83b7f02e/lib/httpi/adapter/http.rb:24:in `initialize'
     # ./vendor/cache/httpi-59eb83b7f02e/lib/httpi.rb:185:in `new'
     # ./vendor/cache/httpi-59eb83b7f02e/lib/httpi.rb:185:in `load_adapter'
     # ./vendor/cache/httpi-59eb83b7f02e/lib/httpi.rb:156:in `request'
     # ./vendor/cache/httpi-59eb83b7f02e/lib/httpi.rb:127:in `get'
     # ./lib/chirpify/hardcodes/callback/darden/base.rb:219:in `call_service'
```

**Comment by rogerleite** [comment]
Alex, your backtrace is telling that httpi is using 'http.rb' adapter.
Maybe you can change httpi adapter via savon settings and try again?
Em 26/06/2015 14:27, "Alex Wait" <notifications@github.com> escreveu:

**Comment by tjarratt** [comment]
Sounds like the underlying adapter for [http.rb](https://github.com/httprb/http.rb) has changed for you, @bobber205. I poked around in their repo for a few minutes this morning, but didn't see any obvious changes that would impact you (certainly nothing like a `#headers` method being removed).

It seems like they get this method on the `HTTP` class by including the `HTTP::Chainable` module. You might want to investigate the underlying dependency, to figure out why it broke, but @rogerleite 's suggestion to just change your adapter to something is also perfectly reasonable, and would probably get your code working against without much trouble.

**Comment by bobber205** [comment]
When I change httpi to 2.4.0, savon functions, while just changing it to 2.4.1 breaks savon.
`rm Gemfile.lock && bundle update` results in only httpi changing. Is the reference to headers a new thing?

**Comment by rogerleite** [comment]
HTTPI 2.4.1 adds [http.rb support](https://github.com/savonrb/httpi/pull/145).
When `HTTPI` adapter is not set, it uses `LOAD_ORDER` to test if the adapter is available and use it.

```
LOAD_ORDER = [:httpclient, :curb, :em_http, :excon, :http, :net_http, :net_http_persistent]
```
Probably, `http.rb` is available on your project (see Gemfile) and now `HTTPI` is using it as adapter.

## Ok! How to fix?

The **easy** way is to set `HTTPI` adapter to `:net_http`, using Savon's settings. Something like:

```
client = Savon.client(
      ...
      :adapter => :net_http
    )
```

**Comment by rogerleite** [comment]
Hi @bobber205. Setting adapter to `:net_http` worked? Can i close this issue?

**Comment by rafaelfranca** [comment]
I may be missing something but if this gem doesn't work when the adapter is `http.rb` why add support to it at first place? Or it is savon that is using something in the httpi API that is not exposed in the `http.rb` adapter? If that is the case why not making all adapters have the same API?

**Comment by mikecmpbll** [comment]
@rafaelfranca i think the reason is that the http.rb adapter in httpi doesn't support latest http.rb changes. what we really need is version locking in the httpi adapters so that they don't get selected if the version is unsupported.

**Comment by rogerleite** [comment]
@rafaelfranca @mikecmpbll is correct. Httpi adapters are "optional" gems, and the dependency version needs to be checked on runtime, and unfortunately, Httpi isn't checking adapters versions. :expressionless:

Sorry for troubles, i'm maintaining as i can, enhancements and suggestions are welcome.
